# Generated by Django 3.2.9 on 2021-11-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="father_last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="father last name"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="mother last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
